export enum ERRORS {
    UNAUTHORIZED = 'Un-Authorized',
    UNAUTHORIZED_ACCESS = 'Un-Authorized Access',
    MISSING_STORE_ID = 'Store Id is missing',
    STORE_NOT_FOUND = 'Store not found',
    MISSING_STORE_NAME = 'Store Name is missing',
    MISSING_CATEGORY_ID = 'Category Id is missing',
    MISSING_CATEGORY_NAME = 'Category Name is missing',
    MISSING_CATEGORY_IMAGE = 'Category Image is missing',
    CATEGORY_NOT_FOUND = 'Category not found',
    INTERNAL_SERVER_ERROR = 'Internal Server Error',
    MISSING_SIZE_ID = 'Size Id is missing',
    MISSING_SIZE_NAME = 'Size Name is missing',
    MISSING_SIZE_IMAGE = 'Size Image is missing',
    SIZE_NOT_FOUND = 'Size not found',
}
